Test for remote datamanager
amadeu01/the-movie-db-client pull request #7
Opened 2018-06-01 05:42 UTC by amadeu01

@ronanrodrigo Eu não acho que fiz da melhor forma. Mas já fiz um pequeno teste.

Eu usei uma lib para fazer o stub. Assim consigo falar o que quero receber de uma resposta para um determinado request.

Encontrei problema para enteder como monta uma Regex com `NSRegularExpression`. Depois vou olhar isso com mais calma. Mas, já queria ter algo para mostrar.

2018-06-02 17:13 UTC, ronanrodrigo requested changes

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/MovieListMocks.swift
> +        var upcomingMovies: MovieUpcomingResponse?
Da uma ajustada na ideação desse arquivo. Ta bem ruim de ler 😕. Você pode selecionar todo o arquivo e apertar `ctrl+i`

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +            try! NSRegularExpression(pattern: "\\Q" + Endpoints.UpcomingMovie.fetch.url + "\\E" + "+", options: [])
É isso que eu não gosto das bibliotecas de teste. É muito código pra setup. Quase que merece um teste pro teste.

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    func testRemoteDataManager_getUpcomingReleases() throws {
O `given`, `when`, `then` é mais apropriado que faça parte do nome do método de teste. E o código de teste você substitui por `arrange`, `act` e `assert`. E no Swif não utilizamos `sanke_cases`

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Given
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //When
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Then
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Given
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //When
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Then
🔥 no comentário

2018-06-02 17:13 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    var networkExpectation: XCTestExpectation?
Essas propriedades podem ser privates

2018-06-02 17:14 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    func testRemoteDataManager_getUpcomingReleases() throws {
E, não precisa de comentários dizendo o que é cada pedaço do teste

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/MovieListMocks.swift
> +        var upcomingMovies: MovieUpcomingResponse?
Feito

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    func testRemoteDataManager_getUpcomingReleases() throws {
Certo!

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Given
Feito

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Then
Feito

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //When
Feito

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Then
Feito

2018-06-02 20:14 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    var networkExpectation: XCTestExpectation?
Feito

2018-06-02 20:16 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +            try! NSRegularExpression(pattern: "\\Q" + Endpoints.UpcomingMovie.fetch.url + "\\E" + "+", options: [])
Então, eu queria ter essa experiência de usar alguma lib como essa.
E, posso mudar isso depois. Em outro PR hehe

2018-06-03 00:29 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +        //Given
Feito

2018-06-03 00:30 UTC, amadeu01 commented
@ronanrodrigo acho que fiz todas as mundaças que você comentou.

2018-06-04 12:28 UTC, ronanrodrigo commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    func testGetUpcomingReleases() throws {
Na issue #2 eu comentei que é uma boa o **nome** da função de teste dizer o que ela está testando. Usando na linha do given/when/then. Então aqui ficaria algo como:

```swift
func testGetUpcomingReleasesWhenFirstPageThenRetriveUpcomingMovie() {
    // ...
}
```

2018-06-04 12:51 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +    func testGetUpcomingReleases() throws {
Show! Vou alterar!

2018-06-06 04:17 UTC, amadeu01 commented
@ronanrodrigo depois dá uma olhada se acha que o PR ficou bom e se tem algo a mais para melhorar ou que não consiga ser aceito 😄 

Eu não sei o motivo mas o appcenter tá quebrando com
`usr/bin/xcodebuild failed with return code: 65`

Vou abrir uma issue para olhar isso depois

2018-06-06 04:19 UTC, amadeu01 commented on The Movie DB ClientTests/MovieList/RemoteDataManagerTest.swift
> +            try! NSRegularExpression(pattern: "\\Q" + Endpoints.UpcomingMovie.fetch.url + "\\E" + "+", options: [])
@ronanrodrigo vou abrir uma issue para mudar isso depois.
Eu queria fazer testes para quando não tem internet e meio que deixar claro o que deve ser o comportamento. E acho que usando essas libs fica ruim para fazer esse tipo de teste 😢 

Bem, o que você comentou do setup é bem verdade. Vou fazer uma issue para alterar isso depois. O lado bom é que consigo ver a evolução do aprendizado com os PR's hehe 😄

2018-06-06 12:40 UTC, ronanrodrigo approved these changes
👍 🎉

2018-06-06 12:48 UTC, merged